### ISSUE TITLE
Typography improve

### ISSUE THREAD

**Issue by nazar-lazarchuk** [dariaharets/project#15]
Pls replace the `span` with yellow text to tag `<strong>`
![image](https://user-images.githubusercontent.com/22054488/128514052-f1b603e4-408a-42dd-8ad8-59f76eff76a4.png)

**Comment by nazar-lazarchuk** [comment]
Also please remove extra tags from navigation links: `<div>`, `<p>`
![image](https://user-images.githubusercontent.com/22054488/128514427-243cb8c0-fe1b-44bf-a2a9-938af7f94f82.png)

**Comment by dariaharets** [comment]
added in new pull request
